### ISSUE TITLE
Audio sound

### ISSUE THREAD

**Issue by dekosan** [hexeguitar/ESP32_TFT_PIO#1]
I used PlatformIO to load on a ESP32_2432_S028 USB-C version board. In the PlatformIO I set the env to default_envs = esp32devCYD_STOCK. Sound mod has been done, PSRAM not yet (ordered memory to do later).
I have some issues:
- Sound files are playing fine, no distortion. BUT at the end of the file playing, it gives a short 'prrt' sound. This with any source (audioConnecttoSD, audioConnecttohost, audioConnecttoSpeech).
- When an sd-card is inserted, the audioConnecttohost does not work, without it works.

Is it correct that both problems are related to the SDRAM not being installed?

Thanks for sharing your work
Kind regards

**Comment by hexeguitar** [comment]
I have only the earlier micro-USB CYD model and used it for this project.
Maybe the USB-C model has some HW changes. Is it the one with two USB (C+micro) sockets?
Have you changed all the resistors in the Audio mod?
Without PSRAM there will be problems with streaming, LVGL takes a chunk of RAM, Audio needs it too for larger streaming buffers. OGG Vorbis and FLAC decoders will not work without PSRAM.
Regarding the SD card - not sure. I think i might be power related. 
[See here](https://github.com/hexeguitar/ESP32_TFT_PIO/blob/main/README.md#5-current-consumption)

With all on (WiFi, card, audio amp, display) the current consumption spikes above 500mA. Maybe try it with a powered USB hub.

**Comment by dekosan** [comment]
Thx for your quick response. The CYD has both micro and USB-C. Also audio
mod has been done. I send feedback when PSRAM is installed.
I also check by later with power bank and more current.
Kind regards

**Comment by hexeguitar** [comment]
Also, it seems the 2xUSB model is missing the 5k1 resistors on the CC1|CC2 lines.

**Comment by dekosan** [comment]
Ok,I’ll check it out.
Thx

**Comment by dekosan** [comment]
Indeed, no resistors on the CC lines. Connecting with an USB-C to USB-C cable  it probably will not work. With an USB-C to USB-A cable, as I use it,  works OK.

**Comment by dekosan** [comment]
I added the memory, PSRAM now available (esp32devCYD_MOD);
- When an sd-card is inserted, the audioConnecttohost works now.
- The "prrt" sound at the end of the audio playing or STOP is still existing.
- Flac files play now.
When playing audioConnecttohost("http://stream.radioparadise.com/flac"); it gives also the "prrt" sounds during playing. When the CYD is close to the wifi source it's less, when more distant it's more. So wifi signal quality seems important. 

So, besides the "prtt" noises, it's working.

**Comment by dekosan** [comment]
correction: "http://stream.radioparadise.com/flac" didn't work, https://stream.radioparadise.com/flac" worked. On my VLC player however, both worked.

**Comment by dekosan** [comment]
FYI, the following links gives good results, no dropouts both at MP3 @ 128 Kbit/s:
audioConnecttohost("https://icecast.vrtcdn.be/radio1-high.mp3/");
audioConnecttohost("https://paradise.stream.laut.fm/paradise");

**Comment by dekosan** [comment]
I upgraded the ESP version 2.03 to 2.017 and the last problem (prttt sound) is solved. All good now.

**Comment by dekosan** [comment]
For me, one of the better CYD projects on the i-net.
